swagger: '2.0'
info:
  title: Pi K8s Fitches Chore API
  version: "0.1"
consumes:
  - application/json
produces:
- application/json
paths:
  /health:
    get:
      operationId: service.health
      tags: [Health]
      summary: Health check
      responses:
        200:
          description: We're good
  /setting:
    get:
      operationId: service.setting_list
      tags: [Chore]
      summary: Settings for dealing with Chores
      responses:
        200:
          description: We're good
  /template:
    get:
      operationId: service.template_list
      tags: [Chore]
      summary: List Chore Templates
      responses:
        200:
          description: We're good
  /chore:
    post:
      operationId: service.chore_create
      tags: [Chore]
      summary: Creates a Chore
      consumes:
        - application/json
      parameters:
        - in: body
          name: chore
          description: The message playload
          schema:
            type: object
            required:
              - template
              - person
              - node
            properties:
              template:
                type: integer
                description: The id of the template to create the chore from
              person:
                type: string
                description: The person assigned to the chore
              node:
                type: string
                description: The node to handle the chore
      responses:
        201:
          description: Chore created
    get:
      operationId: service.chore_list
      tags: [Chore]
      summary: List Chores
      responses:
        200:
          description: We're good
  /chore/{chore_id}:
    get:
      operationId: service.chore_retrieve
      tags: [Chore]
      summary: Retrieve Chore
      parameters:
        - in: path
          required: true
          name: chore_id
          type: string
          description: The id of the chore to retrieve
      responses:
        200:
          description: We're good
  /chore/{chore_id}/next:
    post:
      operationId: service.task_next
      tags: [Chore]
      summary: Completes the current chore task and goes onto the next
      parameters:
        - in: path
          required: true
          name: chore_id
          type: string
          description: The id of the chore to forward
      responses:
        202:
          description: We're good
  /chore/{chore_id}/task/{task_id}/{action}:
    post:
      operationId: service.task_action
      tags: [Chore]
      summary: Completes the specified chore task and goes onto the next
      parameters:
        - in: path
          required: true
          name: chore_id
          type: string
          description: The id of the chore to change
        - in: path
          required: true
          name: task_id
          type: integer
          description: The id of the task to complete
        - in: path
          required: true
          name: action
          type: string
          description: The action to perform
      responses:
        202:
          description: We're good
